tls_codec: Fix variable length encoding
RustCrypto/formats pull request #1084
Opened 2023-05-26 13:18 UTC by pcapriotti

- Lengths over 2 bytes were serialised with an incorrect prefix
- Fixed off-by-one errors on encoding length boundaries
- Length prefix should be the logarithm of the number of bytes to read to extract the length

2023-05-26 15:27 UTC, franziskuskiefer requested changes
Good catch. This hasn't been tested very well.
Can you add test cases for all the edge cases around the boundaries?

The deserialize is actually missing a check that the minimum encoding was used if `feature = "mls"`. Can you add that as well while you're at it?

2023-05-26 15:27 UTC, franziskuskiefer commented on tls_codec/src/quic_vec.rs
> +    } else if length < 0x4000 {
Nice catch. I'd prefer `<=` for these and keep the values.

2023-05-30 07:38 UTC, pcapriotti commented
I added boundary tests and a check that the minimum encoding is used.

2023-05-31 17:17 UTC, franziskuskiefer requested changes
Thanks, one more thing, then we can get this in.

2023-06-01 07:35 UTC, pcapriotti commented on tls_codec/src/quic_vec.rs
> +    if min_len_len != len_len {
Yep, sorry, I forgot to add the feature check. Fixed now.

2023-06-01 08:18 UTC, franziskuskiefer approved these changes
Thanks!

2023-06-01 08:18 UTC, merged