tls_codec: Make constants generated during trait derivation upper case
RustCrypto/formats pull request #1172
Opened 2023-07-31 08:36 UTC by kkohbrok

This PR makes generated constants strictly upper case. This is one way to avoid clippy warnings that occur, when deriving TlsSerialize and others.

2023-08-10 07:59 UTC, franziskuskiefer requested changes
> EDIT: I just realized that the solution in this PR doesn't work in edge cases, where an enum has, for example, an Ok and an OK variant. A better solution might be to just allow non-snake-case constants.

Indeed. Do you want to update the PR to change it to an `allow`?

2023-08-14 09:28 UTC, kkohbrok commented
I tried adding the requisite `allow`s, but it doesn't seem to work. It does work, though, when I expand the macro and use it to implement the trait "manually". So I'm not sure what's going on.

2023-08-15 18:03 UTC, franziskuskiefer requested changes

2023-08-16 05:39 UTC, kkohbrok commented on tls_codec/derive/src/lib.rs
> +                            #[allow(non_upper_case_globals)]
Nice! That does indeed seem to do the trick.

2023-08-16 05:40 UTC, kkohbrok commented
I've moved the allow to the const definitions as you suggested @franziskuskiefer. I've also remove two pre-existing allows that don't really do anything anymore.

2023-08-16 06:13 UTC, franziskuskiefer requested changes
Thanks, there's one more `const` in line 621 that we should probably cover as well or is there a reason that can't throw the warning?

2023-08-16 06:58 UTC, franziskuskiefer approved these changes
Thanks

2023-08-16 07:07 UTC, merged