tls_codec: implement `U24`
RustCrypto/formats pull request #1284
Opened 2023-12-16 03:12 UTC by tnytown

Resolves #1277.

2023-12-16 04:11 UTC, baloo commented on tls_codec/src/primitives.rs
> +                let len = <$t>::default().tls_serialized_len();
This was a `const-fn`, this isn't anymore.

2023-12-28 14:35 UTC, franziskuskiefer requested changes
Sorry for the slow review. Holidays ... 🎄🤶🏻
Generally looks good to me. Two nits then we can get this in.
I quickly checked RFC 9000 but it doesn't seem to allow u24 for variable length encodings but maybe double check that we shouldn't add it for variable length encodings too.

2023-12-28 14:35 UTC, franziskuskiefer commented on tls_codec/src/tls_vec.rs
> +            let len = <$size>::tls_deserialize(bytes)?.try_into().unwrap();
The conversion is probably fine. The `unwrap` may slow down things. Shall we return an error instead?
There are benchmarks that could tell us if this really slows down things. Can you use them to see if you see any significant issue here?

2023-12-28 14:35 UTC, franziskuskiefer commented on tls_codec/src/tls_vec.rs
> +impl_secret_tls_vec!(U24, SecretTlsVecU24, 2);
Should this be `3`?

2023-12-31 11:44 UTC, franziskuskiefer commented on tls_codec/src/tls_vec.rs
> +            let len = <$size>::tls_deserialize(bytes)?.try_into().unwrap();
Cool, looks like this shold be fine then :)

2024-01-04 18:40 UTC, franziskuskiefer approved these changes
Thanks, lets get this in then :)

2024-01-04 18:41 UTC, merged