feat: Implement `tld_codec(skip)` support.
RustCrypto/formats pull request #756
Opened 2022-11-09 14:00 UTC by duesee

This PR implements support for a `skip` attribute on structs. When using ...

```rust
struct StructWithSkip {
  #[tls_codec(skip)]
  a: u8,
  b: u8,
}
```

... only `b` will be serialized. During deserialization we call `Default::Default()` for `a`.

When `Default` is not implemented we get something like ...

```
error[E0277]: the trait bound `NonDefaultField: Default` is not satisfied
  --> tls_codec/derive/tests/attributes.rs:34:14
   |
34 |     #[derive(TlsDeserialize, TlsSerialize, TlsSize)]
   |              ^^^^^^^^^^^^^^ the trait `Default` is not implemented for `NonDefaultField`
```

... which is good enough IMO.

This is a first working version but it may have some problems I overlooked. First time doing something with procedural macros :-) There is also no documentation yet.

2022-11-11 08:49 UTC, franziskuskiefer requested changes
Genereally looks good to me with a few comments inline.

2022-11-11 08:49 UTC, franziskuskiefer commented on tls_codec/derive/src/lib.rs
Can you update the comment on `parse`?

2022-11-11 08:49 UTC, franziskuskiefer commented on tls_codec/derive/src/lib.rs
> +fn function_skip(field: &Field) -> Result<bool> {
Please add comments to function to exaplain what they are doing.

2022-11-11 08:49 UTC, franziskuskiefer commented on tls_codec/derive/src/lib.rs
> +                    .into_iter()
Using `iter` everywhere here and only cloning the `member` when needed should be more efficient.

2022-11-11 08:49 UTC, franziskuskiefer commented on tls_codec/derive/src/lib.rs
> +                let mut tmp_members: Vec<Member> = Vec::new();
Same code as above? Can we pull this out to avoid code duplication?

2022-11-11 08:49 UTC, franziskuskiefer commented on tls_codec/derive/src/lib.rs
> +                let mut tmp_members: Vec<Member> = Vec::new();
Almost the same here.

2022-11-14 10:21 UTC, duesee commented
Thanks for the review. I'll cleanup, deduplicate, and add a bit of documentation.

2022-11-14 13:38 UTC, duesee commented
I used the `trybuild` crate. Not sure if this is too much. But it might be good to already have that in place in case we want to work on user-facing errors in the future. The alternative is, as you said, to use doc comments with `compile_fail` on private functions.

2022-11-15 07:43 UTC, franziskuskiefer commented on tls_codec/derive/Cargo.toml
> +trybuild = "*"
Let's use a version.

2022-11-15 07:50 UTC, franziskuskiefer requested changes
I think using `trybuild` is fine. Only one nit.

2022-11-15 09:08 UTC, franziskuskiefer approved these changes
Thanks

2022-11-15 09:09 UTC, merged

2022-11-15 09:29 UTC, duesee commented
I should have mentioned that I intended to cleanup the commits before merging. It's okay but having "fixups" in the commit history is not great. Sorry for that.

2022-11-15 09:50 UTC, franziskuskiefer commented
It's getting squashed anyway 🙂

2022-11-15 10:03 UTC, duesee commented
Ah, true that :-)